package org.asf.cyan.fluid.mappings;

import org.asf.cyan.api.config.annotations.Comment;

/**
 * 
 * Minecraft mappings object for holding the mojang obfuscation mappings
 * 
 * @author Stefan0436 - AerialWorks Software Foundation
 *
 */
@Comment("Minecraft jar mappings, automatically generated by Cyan MTK on first startup.")
@Comment("These mappings were generated by Cyan MTK by using the official mappings found inside the version json.")
@Comment("Cyan downloads the official mappings on first launch and converts them to CCFG so FLUID can read them.")
@Comment("The mappings have not been included in cyan's distrubuted files and may NOT be distributed according to the minecraft EULA.")
public class Mappings extends Mapping<Mappings> {

	public Mappings() {
		super();
	}

}
