package org.asf.cyan;

import org.asf.cyan.api.config.annotations.Comment;
import org.asf.cyan.fluid.mappings.Mapping;

@Comment("Yarn Compatibility Mappings, automatically generated by Cyan MTK on first startup.")
@Comment("These mappings were generated by Cyan Fabric Support Extension to allow Cyan to run on Fabric.")
@Comment("Cyan downloads the official and yarn mappings on first launch and converts them to CCFG so FLUID can read them.")
@Comment("The mappings have not been included in cyan's jar files and may NOT be distributed! (you can find yarn here: https://github.com/FabricMC/yarn)")
class YarnMappings extends Mapping<YarnMappings> {
	
	public YarnMappings() {
		super();
	}
	
}
