package org.asf.cyan.api.config.annotations;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

/**
 * 
 * The property is does not get generated by default, but can be added (Added if the entry has a comment but disabled/commented the key and content)
 * @author Stefan0436 - AerialWorks Software Foundation
 *
 */
@Retention(RUNTIME)
@Target({ FIELD })
public @interface OptionalEntry {
}
