# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build (1.16.5)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        path: |
            ~/.gradle/caches/Cornflower
        key: ${{ runner.os }}-${{ hashFiles('./config.gradle') }}
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Setup git user email
      run: git config user.email "autobuild@localhost"
    - name: Setup git user name
      run: git config user.name autobuild
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permissions to build script
      run: chmod +x buildlocal.sh
    - name: Grant execute permissions to workflow build script
      run: chmod +x buildworkflow.sh
    - name: Setup LiteCyan libraries for build
      run: ./gradlew -c settings.lite.gradle installLiteLibs
    - name: Build for 1.16.5
      run: ./buildworkflow.sh 1.16.5
    - name: Build for 1.16.5 with Paper support
      run: ./buildworkflow.sh 1.16.5 paper
    - name: Build for 1.16.5 with Fabric support
      run: ./buildworkflow.sh 1.16.5 fabric
    - name: Build for 1.16.5 with Forge support
      run: ./buildworkflow.sh 1.16.5 forge
