# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build (1.17)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permissions to build script
      run: chmod +x buildlocal.sh
    - name: Grant execute permissions to workflow build script
      run: chmod +x buildworkflow.sh
    - name: Setup LiteCyan libraries for build
      run: ./gradlew -c settings.lite.gradle installLiteLibs
    - name: Build for 1.17
      run: ./buildworkflow.sh 1.17
#    - name: Build for 1.17 with Paper support
#      run: ./buildworkflow.sh 1.17 paper
#    - name: Build for 1.17 with Fabric support
#      run: ./buildworkflow.sh 1.17 fabric
#    - name: Build for 1.17 with Forge support
#      run: ./buildworkflow.sh 1.17 forge
