package org.asf.cyan.minecraft.toolkits.mtk;

import org.asf.cyan.api.config.annotations.Comment;
import org.asf.cyan.fluid.remapping.Mapping;

@Comment("Intermediary Compatibility Mappings, automatically generated by Cyan MTK on first startup.")
@Comment("These mappings were generated by Cyan Fabric Support Extension to allow Cyan to run on Fabric.")
@Comment("Cyan downloads the official and intermediary mappings on first launch and converts them to CCFG so FLUID can read them.")
@Comment("The mappings have not been included in cyan's jar files and may NOT be distributed! (you can find intermediary here: https://github.com/FabricMC/intermediary)")
class IntermediaryMappings extends Mapping<IntermediaryMappings> {

	public IntermediaryMappings() {
		super();
	}

}
