package org.asf.cyan.minecraft.toolkits.mtk;

import org.asf.cyan.api.config.annotations.Comment;
import org.asf.cyan.fluid.remapping.Mapping;

@Comment("MCP Compatibility Mappings, automatically generated by Cyan MTK on first startup.")
@Comment("These mappings were generated by Cyan Forge Support Extension to allow Cyan to run on Forge.")
@Comment("Cyan downloads the official and MCP mappings on first launch and converts them to CCFG so FLUID can read them.")
@Comment("The mappings have not been included in cyan's jar files and may NOT be distributed!")
class McpMappings extends Mapping<McpMappings> {

	public McpMappings() {
		super();
	}

}
