package org.asf.cyan.minecraft.toolkits.mtk;

import org.asf.cyan.api.config.annotations.Comment;
import org.asf.cyan.fluid.remapping.Mapping;

/**
 * 
 * Minecraft mappings object for holding the mojang obfuscation mappings
 * 
 * @author Stefan0436 - AerialWorks Software Foundation
 *
 */
@Comment("Minecraft jar mappings, automatically generated by Cyan MTK on first startup.")
@Comment("These mappings were generated by Cyan MTK by using the official mappings found inside the version json.")
@Comment("Cyan downloads the official mappings on first launch and converts them to CCFG so FLUID can read them.")
@Comment("The mappings have not been included in cyan's distributed files and may NOT be distributed according to the minecraft EULA.")
class VanillaMappings extends Mapping<VanillaMappings> {

	public VanillaMappings() {
		super();
	}

}
